site_name: Phenox Library Documentation
theme: readthedocs
#repo_url: https://github.com/phenoxlab/phenox/
repo_url: https://github.com/mthrok/phenox/
site_description: Phenox Library Documentation
site_author: 此村 領
site_favicon: 'favicon.ico'
site_dir: '../../site-doc/ja'
pages:
- 'ホーム': 'home.md'
- 初めに:
    - '初めにお読みください': 'start/note.md'
    - 'Phenox セット内容物': 'start/package.md'
    - '機体構成': 'start/hardware.md'
    - '回路構成': 'start/circuit.md'
    - '機体軸と回転方向': 'start/directions.md'
    - '電源について': 'start/power.md'
    - '通信方法について': 'start/com.md'
    - 'その他の取り扱い': 'start/others.md'
- アプリケーション開発:
    - '開発について': 'dev/dev.md'
    - 'Linux 環境の構築': 'dev/env.md'
    - 'GUIによるパーティションの作成': 'dev/gui.md'
    - 'Phenox ライブラリについて': 'dev/lib.md'
    - 'API' : 'dev/api.md'
    - 'パラメーター一覧' : 'dev/param.md'
    - '状態量一覧' : 'dev/state.md'
    - '用語集' : 'dev/glossary.md'
- チュートリアル:
    - 'プロジェクトのビルド' : 'tut/build.md'
    - 'Phenox の飛行' : 'tut/controll.md'
    - '画像配信サーバープログラム': 'tut/server.md'
- 'FAQ': 'faq.md'
- '付録': 'appendix.md'
